# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from thegame import thegame_pb2 as thegame_dot_thegame__pb2


class TheGameStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Game = channel.stream_stream(
        '/TheGame/Game',
        request_serializer=thegame_dot_thegame__pb2.Controls.SerializeToString,
        response_deserializer=thegame_dot_thegame__pb2.GameState.FromString,
        )
    self.View = channel.unary_stream(
        '/TheGame/View',
        request_serializer=thegame_dot_thegame__pb2.ViewRequest.SerializeToString,
        response_deserializer=thegame_dot_thegame__pb2.GameState.FromString,
        )
    self.Admin = channel.unary_unary(
        '/TheGame/Admin',
        request_serializer=thegame_dot_thegame__pb2.Command.SerializeToString,
        response_deserializer=thegame_dot_thegame__pb2.CommandResponse.FromString,
        )


class TheGameServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Game(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def View(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Admin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TheGameServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Game': grpc.stream_stream_rpc_method_handler(
          servicer.Game,
          request_deserializer=thegame_dot_thegame__pb2.Controls.FromString,
          response_serializer=thegame_dot_thegame__pb2.GameState.SerializeToString,
      ),
      'View': grpc.unary_stream_rpc_method_handler(
          servicer.View,
          request_deserializer=thegame_dot_thegame__pb2.ViewRequest.FromString,
          response_serializer=thegame_dot_thegame__pb2.GameState.SerializeToString,
      ),
      'Admin': grpc.unary_unary_rpc_method_handler(
          servicer.Admin,
          request_deserializer=thegame_dot_thegame__pb2.Command.FromString,
          response_serializer=thegame_dot_thegame__pb2.CommandResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TheGame', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
